// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClesozL2IJOwjZ2hsJ93Om4dCuorJUajo',
    appId: '1:347832975203:web:b579f14107e2e76242dd56',
    messagingSenderId: '347832975203',
    projectId: 'pomoicar',
    authDomain: 'pomoicar.firebaseapp.com',
    storageBucket: 'pomoicar.appspot.com',
    measurementId: 'G-LPBB1YTB19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7op3biA1NbBzhvckWzMs0O_RsQiMltrg',
    appId: '1:347832975203:android:6e2e17b16734555e42dd56',
    messagingSenderId: '347832975203',
    projectId: 'pomoicar',
    storageBucket: 'pomoicar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPjNIBcV0GzowkadCaWGhX1tOwz7VB0U4',
    appId: '1:347832975203:ios:22b3431473f0353442dd56',
    messagingSenderId: '347832975203',
    projectId: 'pomoicar',
    storageBucket: 'pomoicar.appspot.com',
    iosBundleId: 'com.example.pomoikar',
  );
}
